# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.srcs/sources_1/ip/XADC_only_for_template/XADC_only_for_template.xci
# IP: The module: 'XADC_only_for_template' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.gen/sources_1/ip/XADC_only_for_template/XADC_only_for_template_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_only_for_template'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.gen/sources_1/ip/XADC_only_for_template/XADC_only_for_template.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_only_for_template'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.srcs/sources_1/ip/XADC_only_for_template/XADC_only_for_template.xci
# IP: The module: 'XADC_only_for_template' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.gen/sources_1/ip/XADC_only_for_template/XADC_only_for_template_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_only_for_template'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/rikir/Documents/FPGA_projects/Sampler_Pmod_AD1/Sampler_Pmod_AD1.gen/sources_1/ip/XADC_only_for_template/XADC_only_for_template.xdc
# XDC: The top module name and the constraint reference have the same name: 'XADC_only_for_template'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
